spring:
  profiles:
  active: local                                       # email log
  datasource:                                         # db datasource
    url: jdbc:postgresql://localhost:5432/springweb
    username: ssu
    password: 1234
  jpa:                                                # db initialization
    hibernate:
      ddl-auto: create-drop
      generate-ddl: false                             # create true
      show-sql: true                                  # sql log
    properties:
      hibernate:
        format_sql: true                              #sql query formatting

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: trace                         # sql value log
      springframework:
        security: DeBug                             # spring security
        me:
          ssu:
            springquerydslrestapi:
              domains: deBug
#external-api:
#  push: ''

jwt:
  header: Authorization
  authorities_key: auth
  bearer-type: bearer
  secret: c3dpbW1pbmctc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC12YWx1ZS1jcmVhdGUtd2l0aC1iYXNlNjQtZW5jb2RlLXN3aW1taW5nLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC1zZWNyZXQtdmFsdWUtY3JlYXRlLXdpdGgtYmFzZTY0LWVuY29kZQo=
  token-validity-in-seconds: 3600

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false